test

diff --git a/.github/workflows/merge-queue-pipeline.yml b/.github/workflows/merge-queue-pipeline.yml
--- a/.github/workflows/merge-queue-pipeline.yml
+++ b/.github/workflows/merge-queue-pipeline.yml
@@ -39,15 +39,13 @@ jobs:
 # is cancelled.
   merge-queue-pipeline:
     name: Merge Queue Pipeline
-    if: always() &&
-      github.event_name == 'merge_group' &&
-      (cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure'))
+#    if: always() &&
+#      github.event_name == 'merge_group' &&
+#      (cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure'))
+    if: github.event_name == 'merge_group' && (cancelled() || failure())
     needs: [changes, server-ci]
     runs-on: ubuntu-latest
     steps:
       - run: |
-          echo github.event_name: ${{ github.event_name }}
-          echo needs.changes.result: ${{ needs.changes.result }}
-          echo needs.server-ci.result: ${{ needs.server-ci.result }}
           echo "Some workflows have failed!"
           exit 1
